### ISSUE TITLE
Standardize Helm chart structure and documentation to align with best practices

### ISSUE THREAD

**Issue by mattfsourcecode** [mattfsourcecode/ai-kubernetes-gateway#26]
# Improve Helm Chart Structure and Organization According to Best Practices

### Current Structure

```
helm-chart/
├── Chart.yaml
├── values.yaml
├── localai-values.yaml
├── files/
└── templates/
    ├── _helpers.tpl
    ├── deployment.yaml
    ├── models-configmap.yaml
    ├── service.yaml
    └── [other templates]
```

### Recommended Directory Structure Improvements

1. **Remove Unnecessary Directories**

   - Remove the `files/` directory if not storing additional resources
   - Keep chart structure flat and simple according to official Helm conventions

2. **Add Standard Directories and Files**

   ```
   helm-chart/
   ├── Chart.yaml
   ├── values.yaml
   ├── values.schema.json           # Add JSON schema for values validation
   ├── README.md                    # Add detailed documentation
   ├── NOTES.txt                    # Add installation notes
   ├── charts/                      # For subchart dependencies
   └── templates/
       ├── NOTES.txt               # Move here from root
       ├── _helpers.tpl
       ├── tests/                  # Add test templates
       │   └── test-connection.yaml
       └── [organized templates]
   ```

### Documentation Improvements

1. **README.md Enhancements**

   - Add detailed installation instructions
   - Document all configurable parameters
   - Include examples for common use cases
   - Add troubleshooting section
   - Document dependencies and requirements

2. **Chart.yaml Updates**

   - Add comprehensive annotations
   - Include detailed chart description
   - List maintainers
   - Document dependencies
   - Add keywords for discoverability

3. **Code Comments**

   - Add YAML comments in templates explaining complex logic
   - Document default behaviors
   - Explain conditional statements
   - Add parameter validation notes

### Template Organization

1. **Template File Naming**

   - Use consistent prefixes for related resources
   - Follow naming convention: `<resource-type>-<component>.yaml`
   - Example:
     ```
     templates/
     ├── configmap-models.yaml
     ├── deployment-api.yaml
     ├── service-api.yaml
     ├── pvc-models.yaml
     └── ingress-api.yaml
     ```

2. **Helper Templates**

   - Move common code blocks to \_helpers.tpl
   - Create separate sections for different components
   - Add documentation for each helper function
   - Use consistent naming: `{{ template "chart.component.function" . }}`
   - Group related resources in same file when tightly coupled
   - Split large templates into logical components
   - Add clear section separators and comments

### Values File Organization

1. **values.yaml Structure**

   - Group related values into logical sections
   - Add comprehensive comments for each parameter
   - Provide sensible defaults
   - Example structure:

     ```yaml
     # Application Settings
     localai:
         enabled: true
         debug: false
         threads: 4
         contextSize: 512
         modelsPath: "/models"
         apiFormat: "openai"

         image:
         repository: quay.io/go-skynet/local-ai
         tag: v2.5.0
         pullPolicy: IfNotPresent

         # Computing Resources
         resources:
         requests:
             cpu: 500m
             memory: 1Gi
         limits:
             cpu: 2000m
             memory: 4Gi

         # Model Configuration
         models:
         - name: ggml-gpt4all-j
             path: /models/ggml-gpt4all-j
             parameters:
             context_size: 512
             threads: 4

         # Network Settings
         service:
         type: ClusterIP
         port: 8080
         annotations: {}

         ingress:
         enabled: true
         className: "nginx"
         host: "localai.example.com"

         # Storage Configuration
         persistence:
         enabled: true
         size: 10Gi
         storageClass: "standard"
         accessMode: ReadWriteOnce
     ```

2. **Additional Values Files**

   - Keep environment-specific values separate
   - Use consistent naming: `values-<environment>.yaml`
   - Document overrides clearly

This structure follows Helm best practices and will improve maintainability, readability, and usability of the chart.
